datadev_name: nvme1n1
postgresql_dir: "/postgresql"
postgresql_data: "/postgresql/pg_data"
postgresql_arc: "/postgresql/archive"
network: 10.206.210.160/27
gateway: 10.206.210.161
hostname1: pgpogis01
hostname2: pgpogis02
hostname3: pgpogis03
ipnode1: 10.206.210.171
ipnode2: 10.206.210.172
ipnode3: 10.206.210.167
ipvip: 10.206.210.185
pri_net_int: ens5
sec_net_int: eth0
aws_netint_id: eni-0c8d46a7ccd4ac61d