---
- name: Create partition for LVM
  parted:
    device: "/dev/{{datadev_name}}"
    number: 1
    flags: [ lvm ]
    state: present
    part_start: 0%
    part_end: 100%
  register: lvm_format
  tags: prerequisite

- name: Create volume group
  lvg:
    vg: vg_postgresql
    pvs: "/dev/{{datadev_name}}p1"
    state: present
  when: lvm_format is succeeded
  register: vg_create
  tags: prerequisite

- name: Create logical volume
  lvol:
    vg: vg_postgresql
    lv: lv_postgresql
    size: 100%VG
    active: yes
    state: present
  when: vg_create is succeeded
  register: lv_create
  tags: prerequisite

- name: Format volume with XFS
  filesystem: 
    fstype: xfs 
    dev: /dev/vg_postgresql/lv_postgresql
  when: lv_create is succeeded
  register: xfs_format
  tags: prerequisite

- name: Create directory for mount postgresql dir
  file:
    path: "{{postgresql_dir}}"
    owner: postgres
    group: postgres
    state: directory
  when: xfs_format is succeeded
  register: dir_created
  tags: prerequisite 
   
- name: Edit fstab and mount the XFS volume
  mount:
    name: "{{postgresql_dir}}"
    src: /dev/vg_postgresql/lv_postgresql
    fstype: xfs
    opts: "noatime"
    state: mounted
  when: dir_created is succeeded
  register: mounted
  tags: prerequisite

- name: Create directory for mount postgresql data
  file:
    path: "{{postgresql_data}}"
    owner: postgres
    group: postgres
    mode: '0750'
    state: directory
  when: xfs_format is succeeded
  register: dir_created
  tags: prerequisite 

- name: Create directory for mount postgresql archive
  file:
    path: "{{postgresql_arc}}"
    owner: postgres
    group: postgres
    mode: '0750'
    state: directory
  when: xfs_format is succeeded
  register: dir_created
  tags: prerequisite
